# Generated by Django 3.1.1 on 2020-10-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201005_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contratos',
        ),
        migrations.DeleteModel(
            name='ContratPerson',
        ),
        migrations.DeleteModel(
            name='DetallCompra',
        ),
        migrations.DeleteModel(
            name='DirecExtran',
        ),
        migrations.DeleteModel(
            name='DirecLocal',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='ProcesVenta',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Reportes',
        ),
        migrations.DeleteModel(
            name='ReportMerma',
        ),
        migrations.DeleteModel(
            name='ReportVenta',
        ),
        migrations.DeleteModel(
            name='Seguimiento',
        ),
        migrations.DeleteModel(
            name='SeguiProd',
        ),
        migrations.DeleteModel(
            name='Subastas',
        ),
        migrations.DeleteModel(
            name='SubaTrans',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.DeleteModel(
            name='UsuariosUsuarios',
        ),
        migrations.DeleteModel(
            name='VentExtran',
        ),
        migrations.DeleteModel(
            name='VentLocal',
        ),
    ]
