# Generated by Django 3.1.1 on 2020-10-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('productor', 'Productor'), ('interno', 'Interno'), ('externo', 'Externo'), ('consultor', 'Consultor'), ('transportista', 'Transportista')], default='externo', max_length=50),
        ),
    ]
